/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CelvedisRouteImport } from './routes/celvedis'
import { Route as MetodologijaRouteImport } from './routes/metodologija'
import { Route as RazotajiemRouteImport } from './routes/razotajiem'
import { Route as ValstisCodeRouteImport } from './routes/valstis.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CelvedisRoute = CelvedisRouteImport.update({
  id: '/celvedis',
  path: '/celvedis',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologijaRoute = MetodologijaRouteImport.update({
  id: '/metodologija',
  path: '/metodologija',
  getParentRoute: () => rootRouteImport,
} as any)
const RazotajiemRoute = RazotajiemRouteImport.update({
  id: '/razotajiem',
  path: '/razotajiem',
  getParentRoute: () => rootRouteImport,
} as any)
const ValstisCodeRoute = ValstisCodeRouteImport.update({
  id: '/valstis/$code',
  path: '/valstis/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celvedis': typeof CelvedisRoute
  '/metodologija': typeof MetodologijaRoute
  '/razotajiem': typeof RazotajiemRoute
  '/valstis/$code': typeof ValstisCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celvedis': typeof CelvedisRoute
  '/metodologija': typeof MetodologijaRoute
  '/razotajiem': typeof RazotajiemRoute
  '/valstis/$code': typeof ValstisCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celvedis': typeof CelvedisRoute
  '/metodologija': typeof MetodologijaRoute
  '/razotajiem': typeof RazotajiemRoute
  '/valstis/$code': typeof ValstisCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/celvedis' | '/metodologija' | '/razotajiem' | '/valstis/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/celvedis' | '/metodologija' | '/razotajiem' | '/valstis/$code'
  id:
    | '__root__'
    | '/'
    | '/celvedis'
    | '/metodologija'
    | '/razotajiem'
    | '/valstis/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelvedisRoute: typeof CelvedisRoute
  MetodologijaRoute: typeof MetodologijaRoute
  RazotajiemRoute: typeof RazotajiemRoute
  ValstisCodeRoute: typeof ValstisCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celvedis': {
      id: '/celvedis'
      path: '/celvedis'
      fullPath: '/celvedis'
      preLoaderRoute: typeof CelvedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologija': {
      id: '/metodologija'
      path: '/metodologija'
      fullPath: '/metodologija'
      preLoaderRoute: typeof MetodologijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/razotajiem': {
      id: '/razotajiem'
      path: '/razotajiem'
      fullPath: '/razotajiem'
      preLoaderRoute: typeof RazotajiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valstis/$code': {
      id: '/valstis/$code'
      path: '/valstis/$code'
      fullPath: '/valstis/$code'
      preLoaderRoute: typeof ValstisCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelvedisRoute: CelvedisRoute,
  MetodologijaRoute: MetodologijaRoute,
  RazotajiemRoute: RazotajiemRoute,
  ValstisCodeRoute: ValstisCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
